name: Go

on:
  push:

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Module tidy
        run: go mod tidy

      - name: Fmort
        run: go fmt ./...

      - name: vet
        run: go vet ./...

      - name: Check
        run: git diff --exit-code

      - name: Test
        run: go test -v ./...
